
dist: focal
language: node_js
node_js: 
  - 16


before_install:
- echo -e "PRIVATE_KEY="cRAqDHuaVerhDwmcx6CyimbEJvPhGjMEKeMKr6N1osD79PnbTYQm"" > .env

jobs:
  include:
    - 
      os: linux
    - 
      os: osx
      script:
        - npm i
        - npm t
