dist: bionic
language: node_js
node_js:
 - 14
 - 16
os:
  - linux
  - osx
  - windows

before_install:
#  - npm i -g npm@latest
  # install rust to build circom
  - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
  # build circom
  - git clone https://github.com/iden3/circom.git
  - cd circom
  - cargo build --release

install:
  # install circom
  - cargo install --path circom

#   - |
#     if [ $TRAVIS_OS_NAME == "windows" ]; then
#       npm install -g node-gyp
#       npm install --global --production windows-build-tools
#     fi

script:
  - npx scryptlib download
  - npm t