
dist: focal
language: node_js
node_js: 
  - 16
  - 18


before_install:

jobs:
  include:
    - 
      os: linux
    - 
      os: osx
      script:
        - npm i
        - npm run build
        - sed -i 's/process.env.PRIVATE_KEY/scrypt_ts_1.bsv.PrivateKey.fromRandom("testnet").toWIF()/' dist/tests/privateKey.js
        - npm t
