dist: bionic
language: node_js
node_js:
 - 14
 - 16
os:
  - linux
  - osx
  - windows

# before_install:
#  - npm i -g npm@latest


install:
  - |
    if [ $TRAVIS_OS_NAME == "windows" ]; then
      npm install -g node-gyp
      npm install --global --production windows-build-tools
    fi

script:
  - npx scryptlib download
  - npm t