language: node_js
node_js: 
  - 14

jobs:
  include:
    - 
      os: linux
      dist: focal
    - 
      os: osx
    - 
      ox: windows
    - if: branch = master AND type = push
      before_install:
      script:
        - npx scryptlib download
        - |
          npm run download:circom
        - npm run test:all
    - if: branch != master OR type = pull_request 
      script:
        - npx scryptlib download
        - npm t
