dist: focal
language: node_js
node_js:
  - 16

before_install:

os:
  - linux
  - osx
  - windows

script:
  - npm t
  - echo "PRIVATE_KEY=$PRIVATE_KEY" > .env
  - if [ $TRAVIS_EVENT_TYPE == "cron" ] && [ $TRAVIS_OS_NAME == "linux" ] ; then npm run testnet; fi

notifications:
  slack:
    secure: YPJfSbRTEqxXQPwmr1F3L/KFoqaYl102aZoM58uyYssNM2vdgC00B33QYURin6CdDLS/6vS+XRnvjk1fwBaNslimMrc0ssYO27/pS6cHpUHlrunI4NVLar/UZByJVvVWcLke3BMdy+1qb6gNLWjYflHyR/Gy1XfUalhOWG+TCr/iHtphFTVxrjiJqDDACf3DL4unLSV6aOC0nzrm/ypkIeUsjlIG/XrmVBAT2ZWLp6thGaddUD/iTpeDL4X4hUYkErTMdn+YJAOmp/uzJK6MId/kRWRSRoO4ou2gf3dn89oGOJkzlFWjgndH/zuhfk+1LC0vRFltRL/09whNa8giWpzE4agHNINxzuyVRwLRU3dSFGfgjZTTG24s840uWWxKSzwp3btWklClvhDVeSbPs0LIwOmx8i49tqrGrlRGEzefK+wPe4+7PJMyFOGOR79PR0XNJ5JPQkuYbak3wrr30rvyNRebLWwLQCA5kQ045cCwJ1AHbGSzPTEMQGVo+cpEXW5Z62GeZn9NnJHSYzO+qENHnTcuEi/eMt5niVqktpTmuxcmGrpq+W4WFiAhPEtfYSwSzlJZX/ZbAb8tw9yLKYC9D4dkAFAyYg/J1sy3ZEvJ4F4NvJ66zDZw8gPOytp8A4mtAL3LHJ0YgxQPtiTmVGqXx7W2flH+scFwiKmtgOA=
