
dist: focal
language: node_js
node_js: 
  - 14

before_install:
  - npx scryptlib download

jobs:
  include:
    - 
      os: linux
    - 
      os: osx
    - 
      ox: windows
    - if: branch = master AND type = push
      before_install:
      script:
        - npm run download:circom
        - npm run test:all
    - if: branch != master OR type = pull_request 
      script:
        - npm t
